[workspace.package]
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/lucas-montes/rsysaas"
authors = ["Lucas Montes <lluc23@hotmail.com>"]

[workspace.dependencies]
envy = { path = "envy" }
serde = { version = "1.0.163", features = ["derive", "rc"] }
serde_json = "1.0.96"
sqlx = { version = "0.7.0", features = ["sqlite", "runtime-tokio", "tls-rustls"]}
clap = "4.3.19"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"


[package]
name = "webservice"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
# Webserver
axum = { version = "0.6.18", features = ["headers", "json", "query", "http2", "macros", "tracing", "ws"] }
axum-server = { version = "0.3", features = ["tls-rustls"] }
headers = "0.3"
hyper = { version = "0.14.26", features = ["full"] }
tokio = { version = "1.28.2", features = ["full"] }
tokio-stream = "0.1.14"
tokio-tungstenite = "0.19"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace", "cors", "set-header"] }
serde_urlencoded = "0.7.1"

# Recsys
#rec_rsys = { git = "https://github.com/lucas-montes/rec_rsys.git" }
rec_rsys = {path = "../rec_rsys/"}

# Cache
redis = { version = "0.23.0", features = ["json", "serde", "serde_json", "aio", "tokio", "tokio-comp"] }

# Logging
tracing = { workspace = true}
tracing-subscriber = { workspace = true}
tracing-appender = { workspace = true}

chrono = "0.4.23"
sqlx = { workspace = true}
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
serde = { workspace = true}
serde_json = { workspace = true }
clap = { workspace = true }

# Custom
envy = { workspace = true }
aromatic = { path = "aromatic" }
jsonwebtoken = "8.3.0"


[workspace]
members = [".", "envy", "aromatic"]

[profile.release]
opt-level = "z"  # Use the highest optimization level for production builds
lto = true       # Enable Link Time Optimization for better performance
panic = "abort"  # Abort on panic to prevent unwinding overhead
debug = false    # Disable debug symbols to reduce binary size


[profile.dev]
debug = true     # Enable debug symbols for development builds

