[package]
name = "webservice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["headers", "http2", "macros", "tracing", "ws"] }
hyper = { version = "0.14.26", features = ["full"] }
rec_rsys = { path = "../rec_rsys" }
redis = "0.23.0"
serde = { version = "1.0.163", features = ["derive", "rc"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
tower = "0.4.13"
