[package]
name = "webservice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["headers", "http2", "macros", "tracing", "ws"] }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
headers = "0.3"
hyper = { version = "0.14.26", features = ["full"] }
#rec_rsys = { git = "https://github.com/lucas-montes/rec_rsys.git" }
rec_rsys = {path = "../rec_rsys/"}
redis = { version = "0.23.0", features = ["json", "serde", "serde_json", "aio", "tokio", "tokio-comp"] }
serde = { version = "1.0.163", features = ["derive", "rc"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
tokio-stream = "0.1.14"
tokio-tungstenite = "0.19"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
models = { path = "models" }
sqlx = { version = "0.7.0", features = ["sqlite", "runtime-tokio", "tls-rustls"]}
#migrations = { path = "migration" } # depends on your needs

[workspace]
members = [".", "models"]
