version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/myapp
    ports:
      - 8000:8000
    depends_on:
      - redis
