[package]
name = "models"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "models"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.163", features = ["derive", "rc"] }
serde_json = "1.0.96"
